### ISSUE TITLE
Lighthouse

### ISSUE THREAD

**Issue by SnakeSortITA** [Keriew/augustus#1062]
Hello everyone.  I wouldn't want to have found a bug inherent to the Lighthouse.  because even though there is a wood storage nearby it is not loaded and always remains at 0!!!
![photo_2024-03-31_11-53-44](https://github.com/Keriew/augustus/assets/161051551/a8fcd002-c03b-4e79-a65f-4a3a4b1f826e)
![photo_2024-03-31_11-53-47](https://github.com/Keriew/augustus/assets/161051551/3b57d79c-c9c2-41b5-82da-68f25066d600)

**Comment by crudelios** [comment]
Hi, this may be due to one of these reasons:

- you've set timber to stockpile globally
- you've set timber to stockpile on that specific warehouse - check one ofthe lower right buttons on the warehouse properties window
- you've disabled access to the market lady from the Warehouse, which is required for the Lighthouse cartpusher to fetch timber

**Comment by ben-strasser** [comment]
Thanks for the hint with allowing the market lady access to the woos warehouse! I missed that one to. Now, it works for me. :D

I think the UI could use a slight improvement here as it is not obvious that this is necessary.

**Comment by SnakeSortITA** [comment]
I confirm. thanks again for the help. As said by the user above, the method of receiving the lighthouse should be modified, perhaps by introducing its own cart that automatically goes where there is wood for collection. because this is not very intuitive

**Comment by crudelios** [comment]
Yes, this isn't very intuitive. I'm guessing a way to improve it was to add text next to the icons.

I'll think about a way to improve this, but for now I'll close this issue.
