### ISSUE TITLE
vertical alignment of food

### ISSUE THREAD

**Issue by destinationwalker** [Keriew/augustus#1068]
again latest unstable 152:
seem like the vertical alignment of the food goods is not centered correctly.
![vertical alignment](https://github.com/Keriew/augustus/assets/159162256/e4bb7e98-818f-4224-8d6a-9c291ee9e2e3)

**Comment by crudelios** [comment]
Hey!

Yeah, this is a visual issue since the original game. It's not just here but in most places food icons are shown.

Besides not looking very good, there really is no problem with this. And "fixing" it would take a while since I'd have to go thorough all the existing food icons in the game.

I've been meaning to fix this for a few years now, but haven't still done it.  Maybe one day...

Anyway, for that reason, I'll be closing this issue.

Thanks!
