### ISSUE TITLE
Obey system's auto-rotation setting.

### ISSUE THREAD

**Issue by RepairUnit3k6** [Keriew/augustus#1111]
Describe your improvement here.
Keep in mind that UI improvements which require new texts will most likely be declined because we can only work with the original text files. Also, large UI changes will not be accepted.

Basically, you can enable or disable screen auto rotation on your phone. Most ROMs will give you manual rotation button when you flip your phone sideways. Some people like to lie on side and play landscape games and have auto-rotation disabled. Game dosent respect this setting and flip around like fucking merrygoround which woulnt be that bad if rotating screen didnt ocasionally glitched out causing severe visial glitches rendering save menu unusable loosing game progres.

**Comment by crudelios** [comment]
I hear your plight, but unfortunately there's nothing we can do to fix it.

The issue is caused by the library we use to draw graphics and handle input, and afaik they've been aware of the problem for years and, if I remember well, don't consider it a true problem that needs fixing.

Same for the graphics issues. I can't find any proper solution for that, and believe me I tried to fix the problem for years too.
