### ISSUE TITLE
Strange logic of a worker from the guild of architects

### ISSUE THREAD

**Issue by eugenikus8** [Keriew/augustus#1123]
Strange logic of a worker from the guild of architects. Architects do not want to take a resource (marble) from the warehouse closest to the construction site, but take it from one further away.

![2024-06-15_231447](https://github.com/Keriew/augustus/assets/51211736/d7fe0164-e4b2-43f2-9e7e-2005cfeb2c12)

[55555bug.zip](https://github.com/user-attachments/files/15854911/55555bug.zip)

upd
Did some research
If access to the work camp is denied in the lower warehouse, then the architects will not appear at all
If the bottom warehouse is removed, then everything works well.

**Comment by Keriew** [comment]
Not strictly a bug, but I agree it's worth addressing. Monument foremen prefer warehouses that have more resources, because then they can be sure that it will still be there when they arrive. The principle is reasonable, but I think it was overvaluing full warehouses a bit.

Adjusted and fixed in 56bae66.
