### ISSUE TITLE
A Request for Chinese Localization

### ISSUE THREAD

**Issue by BrentAlencar** [Keriew/augustus#1140]
I would like to request that you consider adding Chinese language support to the game. My mother is a big fan of this game, but she's unable to play it due to the language barrier. It would mean a lot to her and many other Chinese-speaking players if the game were available in Chinese.

I am a native Chinese speaker and I would be happy to volunteer my translation skills to assist in the localization process.

Thank you for your time and consideration.

**Comment by crudelios** [comment]
Hello!

There's already a Chinese translation for the game:

https://www.dropbox.com/scl/fo/6ge16vb3jfutda7y0e28q/ABDFFbEkVV1eHjpK_VBnhEk?rlkey=0fsxeltx3kaouswi8k3qrtugu&e=1&dl=0

You have both the traditional and simplified Chinese translation.

That should cover most of the base game, but some of the new Augustus strings haven't been translated.

To use the translations, download the file, unzip it abre extract the folder to your main C3 install folder. Then select the language from the Options menu.

You can also find the Augustus translations on`src/translation/` and there is both a `simplified_chinese.c` and a `traditional_chinese.c` with all the strings. However you'll need to compare to `english.c` to check the missing strings, which isn't that easy.

@Keriew is there an alternative for that?

**Comment by BrentAlencar** [comment]
@crudelios Thank you beyond words!

**Comment by Keriew** [comment]
If you are interested in translating the missing lines (there are a bunch, but they *mostly* deal with editor), then I have a script which extracts missing translated lines. Here's the zip with the missing translation strings, only the parts on the right in the quotes ("") need to be translated. Though, from what other people who handles the Chinese translation said, it isn't straightforward, because the list of supporter characters/hanzi is somewhat limiting.

But if you are interested, we'd be grateful for the help, here's the missing lines:
[missingtranslations.zip](https://github.com/user-attachments/files/16828805/missingtranslations.zip)

**Comment by BrentAlencar** [comment]
Thank you very much. I will try to finish it and compare it to the existing
translations to make it consistent in expression.

Keriew ***@***.***> 于2024年9月1日周日 20:10写道：
