### ISSUE TITLE
Devolving villas or palaces should devolve towards a road

### ISSUE THREAD

**Issue by pavel-klavik** [Keriew/augustus#116]
Currently, devolving villas or palaces when decreasing size will devolve towards a fixed direction (north in the starting rotation). This leads to devolving away from the road and disappearing of the building when devolving from palace to 2x2 house. I would change this to devolve the house always towards a road.

**Comment by subatron** [comment]
While I don't disagree, GamerZakh has pointed out, and it's easy enough to play around, that your walkers can service houses TWO tiles away. So even if your villa devolves 1 tile from the road, it's okay because your market ladies and religious walkers will still work fine. Plus the building evolves back toward the road.

**Comment by crudelios** [comment]
It's not easy to evolve housing towards a road, however to remedy this I made it so the split 1x1 house tiles do not lose education/entertainment/health/religion coverage as they did, so they won't devolve into tents. Therefore if the villas disappear, the 1x1 medium insulaes can immediately grow (because they then have the room) and transform into villas.
