### ISSUE TITLE
Undoing deleting building allowing villa to grow breaks the building

### ISSUE THREAD

**Issue by pavel-klavik** [Keriew/augustus#120]
I had a statue blocking evolution of a 2x2 villa into 3x3 villa. I removed it but it evolved wrongly, so I undoed my action. The image of villa got back smaller, but the game thought that it is 3x3 and I got multiple villa sprites overlapping. I tried to delete them but one 2x1 sprite got stuck there.

**Comment by crudelios** [comment]
I had a look at this one a while ago and due to the way undo works it's neither easy to restore the villa info nor to disable undo when the villa evolves without a major refactor of the code (or even removing undo altogether).

This is also an original C3/Julius bug.

That being said, I think this is unfixable right now, so I'm closing it.
