### ISSUE TITLE
Should busy roads slow down people moving across them?

### ISSUE THREAD

**Issue by gabrer** [Keriew/augustus#127]
Should busy roads slow down people moving across them?

This would incentivise players in thinking towards novel ways to organize streets.

**Comment by LordBaal** [comment]
I would think so, but also offer either wide roads (could be something merely graphical or a road that actually occupy two tiles wide), or offer different kind of roads, dirt roads, crude stone roads, cobbled roads.... with different prices to balance it out.

Or if payment have to be done for road maintenance like in Caesar II then this would put more strain to it, having large non useful roads would put strain on your economy.

Perhaps a combination of both things. Dirt roads are slower or have less capacity clogging quicker but have no or almost no maintenance cost, while paved roads are supreme but cost way more to build and have a cost more to maintain.

**Comment by cdsmith-umn** [comment]
I don't think travel should be slowed unless I can control things like how many children the market ladies get. I doubt that many people are building cities with many low traffic roads. If you're not using roadblocks, then you're definitely already minimizing the number of roads so as to reduce the number of intersections and, therefore, decision points. I suppose that if you're using roadblocks, then you might be using a sub-optimal road network design. By the same token, some of these maps are really tight and have a comparatively high population requirement. So how many useless roads can you truly build?

Also, I disagree with LordBaal that dirt roads should have no maintenance cost, since (in real life) the more traffic across a dirt road, the higher its maintenance costs are. Paved roads cost more to build and have lower maintenance costs; unpaved roads are relatively cheap to build and have higher maintenance costs when they are major thoroughfares.

If this suggestion is added, I will be interested to see how it changes gameplay. Hopefully, it will be a configuration item so that people who dislike it can disable it.

**Comment by LordBaal** [comment]
Dirt roads in my experience the kind of dirt roads that are in the game have 0 maintenance because people don't actually build them and support them more just happen to be made by the relative high traffic between two points in the wilderness. Indeed they don't work very well with heavy use specially in rainy seasons or places. Some dirt roads are put on place but those are different, unless I'm being not imaginative enough for what the dirt roads represent on the game (which is a high chance).

I was talking more about gameplay mechanics than real life however, as if you are introducing making busy streets slower, there must be a trade off for it or a mechanic that help the player cope with it and those mechanics need it counter balance too.

Now for realism sake dirt roads should appear on their own whenever citizens walk on the wilderness on the same tiles repeatedly, and yes paved roads should be expensive and slow to build (if building times were part of the game) but far more durable. If width of road could be implemented somehow all this could be more realistically done, however I feel this would not be possible without changing the game completely.

Hence why having some road categories and making them have different capacities/speeds and prices for title is the only way forward that I see. To offset the real chance people would only bother building the better roads then you need to introduce incentives for it, like upkeep. The simplest way would be the better the road, the higher upkeep per title and call it a day.

However, going further, as cdsmith-umn says, dirt road with high traffic actually need more maintenance, so an organic way to force the player to upgrade paths would need variant upkeep not depending on the type of road but instead of it's use. Each kind of road could have a multiplier for upkeep and/or speed, so while dirt roads are cheaper to build and maintain as long they are low in use, once they hit peak capacity their upkeep skyrockets and/or the speed it offers gets lower. While better kind of roads have a significantly low multiplier so they don't change much the speed/upkeep with the use.

This are just suggestions of course.

**Comment by cdsmith-umn** [comment]
@LordBaal You make good points about roads in games. However, in this game, roads have to be placed by the player; they aren't organically created simply by having walkers go over the same paths time and again. The only walkers in this game that I have seen that can traverse a space that lacks roads are the cart pushers, and then only if you've enabled the configuration item that enables them to do so.

I guess at this point that I am confused about what it is that is being suggested to be changed about roads in this game, at all - even starting with gabrer's suggestion. I can't really see any way to approach road placement in any novel way, as he suggests, since walkers have to be within two tiles of a building to provide their service or good to that building (not to mention the fact that houses have to be within two tiles of roads). When you couple that with the fact that every intersection is a decision point where a walker must choose their direction, then you end up with cities with as few intersections as possible and where the buildings that provide the goods and services to houses end up as close as practical to the houses in order to ensure maximum availability of those goods and services. This leads to forcing all the priests, entertainers, market ladies, bath house ladies, prefects, engineers, cart pushers, and so on onto the same set of streets, with the ultimate goal being that the walkers have the shortest and most consistent routes possible.

I don't think it would bother me to have some kind of maintenance cost attached to streets, though I'm not sure it's practical, useful, or relevant for this game. I don't think that having the walkers slowed down because a street is busy would really have any meaningful impact on gameplay. I use a block design that is 21 tiles long and six tiles wide (including the roads) and I can't see walkers being slowed down having any impact on my city design whatsoever.  The block design allows more than enough space for amphitheaters, theaters, temples, schools, hospitals, libraries, bath houses, fountains, engineers, prefects, and markets. I put warehouses, actor colonies, gladiator schools, and lion houses at one end, with granaries at the other end. I typically build them in pairs, which allows me to space the two housing blocks such that I can fit colosseums between them when I want to do that. They're pretty much self-sufficient/self-contained and gives me precise control over food and resource distribution.

**Comment by Legionary2** [comment]
Hello all. Augustus will certainly be including upkeeps such as temple levy , wall levy tower levy and other aspects to help keep costs down etc. But for roads it is very complex since the game and it’s walkers are so heavily based around them. So for now I don’t think we would go that route.

**Comment by cdsmith-umn** [comment]
@Legionary2 The idea for these levies sounds interesting. Is there somewhere that you all are discussing this idea so that players can read about it and get a better feel for what you're kicking around? (And possibly to have some input?)

**Comment by crudelios** [comment]
In addition to what Legionary2 said, this being a roman city builder, we can't think about traffic in modern terms.

In the game the roads are used by people and, in some cases, by cartpushers. In actual ancient Rome it was more or less the same. It would take an insane amount of people to affect traffic flow in a way that we could consider relevant. So I don't that aspect is worth simulating in the game.

**Comment by gabrer** [comment]
> In addition to what Legionary2 said, this being a roman city builder, we can't think about traffic in modern terms.
> 
> In the game the roads are used by people and, in some cases, by cartpushers. In actual ancient Rome it was more or less the same. It would take an insane amount of people to affect traffic flow in a way that we could consider relevant. So I don't that aspect is worth simulating in the game.

I am sure where you drew that conclusion from, but from a historical point-of-view, it is well-known that many roman routes were utterly busy and the roman administrators put in place several strategies to avoid traffic (especially in big cities, like the ones simulated in Caesar 3).
Just to mention one as an example of the many work in this field, this is a research paper showing how Romans put traffic laws about: << **fixed traffic circulation**, including zigzag and parallel routes, and routes around the forum. **The forum itself was never accessible for wheeled traffic, only for pedestrians**>>.
["Traffic Policy and Circulation in Roman Cities", _C. van Tilburg_ 2011](https://www.jstor.org/stable/24592531?seq=1)

On the other side, I would agree with Legionary2 arguments about the trade-off to keep a balance between realism and game complexity in terms of game dynamics and code managment.

**Comment by crudelios** [comment]
Well, you do have a point there. Though I still think only the central parts of the cities could have traffic problems because of the affluence of people, especially with smaller roads. Or maybe other parts as the lack of planning led to a narrow road becoming a major artery of the city.

However, C3 has a very decentralized way of working though. You don't have a main forum or market where people flock to, rather you have many markets (and even other big buildings like colosseums) that serve a limited part of the city.

Also, even though the game walkers are more or less symbolic, I don't think there's visually enough of those to make a city look to have traffic problems, even on the roads with most walkers. If you look at a game like cities skylines you can see the huge pile of cars and conclude "this is a problem", but that wouldn't be the case in C3 because there aren't nearly enough walkers.

The whole "people distribution" simulation in C3 is out of whack with reality. Making traffic work reliably in such a system seems difficult...
