### ISSUE TITLE
One Window Information Panel to Markets, Granaries and Warehouses

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#162]
I leave 3 suggestions to change the (one window) information panel of markets, granaries and warehouses:

![Market_final](https://user-images.githubusercontent.com/64329357/100529074-74ac9b80-31db-11eb-86ba-fd7065059594.jpg)

![Granary_final](https://user-images.githubusercontent.com/64329357/100529390-184b7b00-31df-11eb-9fe7-e4a94859c37a.jpg)

![Warehouse_Final](https://user-images.githubusercontent.com/64329357/100529140-3663ac00-31dc-11eb-9127-b2b6334912c4.jpg)  ![Warehouse_Scroll](https://user-images.githubusercontent.com/64329357/100530895-9283fb80-31ef-11eb-900c-57dd6ec5514c.jpg)

**Comment by theradeonxt** [comment]
Hi @arkimedes1967 
I like the additional info to show for example the Granary and market what their workers are getting, under the employees box.
Also the scrollbar feature for resources, which currently are fixed types and just fit those windows.

Just one thing that comes into my mind - about the layout to show this info.
From what I know all the buildings show their employment status first.
In your suggestion doing such a change I assume would complicate the coding for the Warehouse, Market, Granary windows.
Indeed, it would save one click, instead of going to "Special orders".
But actually keeping the employment info separate to resources info may be desired in this case.
Furthermore, if they have all info in this page as you can see the scrollbar region is just around half the total window size, which makes it less visible at first glance - assuming all resources fit, which is the case now.

**Comment by arkimedes1967** [comment]
(...) the **scrollbar region is just around half the total window size, which makes it less visible at first glance** - assuming all resources fit, which is the case now.

The scrollbar only makes sense if the commodities can be automatically sorted: (1) getting goods, (2) accepting goods & (3) not accepting goods - as my suggestion shows. As you know, by experience, the clever use of granaries and warehouses says not to accept or getting more then 2 commodities at the same time. On the oder hand, the special orders limits it to a minimum of quarter of the space available (6-12-18-24 to granaries and 8-16-24-32 to warehouses), meanning - it maters only the first 4 visible commodities.

In actual context is the "**Become the trade center**" option still necessary? My opinion is **NO**.

Finally, there's presently a conflict (loop) between "**Start emptying warehouse**" and "**Getting goods**" orders: it starts emptying goods and they'll immediately return again. To fix this, the "start emptying warehouse" should ignore "Getting goods" and "Accepting goods" orders and only emptying the commodities with "not accepting orders".

**Comment by crudelios** [comment]
This issue now has about 3 or 4 separate issues, which doesn't help us filter through problems.

Regarding the main idea of having the special orders on the main window: although the idea is good, there's a point of diminishing returns in fixing issues. The UI code for Julius/Augustus is hard to work with, so this would take a lot of effort to implement (which could be spent adding new features), only to save a single mouse click.

Granted, if someone would come forward to implement this correctly, we would probably accept it, but I doubt any of the developers wants to delve into this. Having created the military sidebar (a major UI project), I know I don't!

**Comment by dLantee** [comment]
Having control on the market what type of food it accepts I thing is a need therefore we can have more control what type of city district we can build (plebs or patricians).In addition when we are sort of certain type of food we have more control where to  distribute it, making sure certain districts won't demote.

**Comment by crudelios** [comment]
As I said before, this is not a bad idea "per se", but it's not a priority right now and thinks work well enough as they stand.

Since this isn't going to be changed for the near future, I'm closing this issue.
