### ISSUE TITLE
Building corruption: large insulae is instead a tower?!

### ISSUE THREAD

**Issue by theradeonxt** [Keriew/augustus#167]
I've played Alesito's map from here: 
http://caesar3.heavengames.com/downloads/showfile.php?fileid=1547

I assume it has happened while placing walls and towers, but in another area of the map.

That block of 2x2 house should be a medium or large insulae.
However, right clicking it shows a Tower menu.
Also a wall appeared in a corner for some reason.

![Untitled](https://user-images.githubusercontent.com/13402104/101673565-0203b180-3a60-11eb-83aa-20230dddf6be.jpg)

![Untitled2](https://user-images.githubusercontent.com/13402104/101673615-15168180-3a60-11eb-8055-937ade18a88d.jpg)

If I try to delete the building it does nothing.
Afterwards right clicking on it got the game frozen, but infact it was showing this invisible menu (right clicking gets out of it):

![Untitled3](https://user-images.githubusercontent.com/13402104/101673584-0a5bec80-3a60-11eb-860c-df58c61aee78.jpg)

**Comment by theradeonxt** [comment]
I add here a save file in that location:

[Alesito-Alone-364BC.zip](https://github.com/Keriew/augustus/files/5668049/Alesito-Alone-364BC.zip)

**Comment by crudelios** [comment]
I had a look at this one.

Somehow your insulae got linked to an existing tower. You can check it out: if you delete the insulae, one of the four towers in the northernmost corner of the map (close to a farming spot) will also get deleted.

Do you remember the context in which you built that tower? Were you building while paused, did you use undo..?

Thanks!

**Comment by theradeonxt** [comment]
Thanks for the input,

I've looked again and from what I can see it may have to do with the undo.

- That exact tower and some walls near was destroyed when I was attacked by natives earlier in the scenario IIRC.
- While rebuilding things I did use undo and pause + some shortcuts assigned to build roads and houses.

Also there are 2 houses which are affected, after deleting all my walls and towers I was able to delete some near them but I still get left with these 2 houses which are now linked to eachother.

- Attempting to delete noe also highlights with red the other one (I had the shovel cursor over it in the picture).
- Of course, deleting does nothing (no not even towers)

![Untitled](https://user-images.githubusercontent.com/13402104/102237843-c2284880-3efd-11eb-977a-90cc4c7a1d61.jpg)

**Comment by crudelios** [comment]
That house link makes sense too. Here's a description of the bug:

The map tile gets tied to a building ID that wasn't placed in that tile but in another one (originally the tower). That's why if you delete the house tile, the tower disappears.

When the tower disappears, the tile it's placed on is assigned to the building ID of "no building", while the bugged tile still points to the ID of the tower (which is now invalid). That's why, when you right-click the tile, the game seems to freeze.

However, as new buildings are created, they will eventually fill that ID again. In your case, the ID was filled with another house, hence a new link was created.

Sadly the only way to fix this is to manually edit the game code for your savegame.

Regarding the underlying issue: I'm thinking it's related to a house developing while using undo, but I'm not entirely sure. Undo has many bugs which are not easy to fix. A way to prevent this is to disable undo when a house evolves or devolves, but I'm not entirely sure it's possible to do that (I had a look once trying to fix a similar bug but had no luck).

**Comment by crudelios** [comment]
I have changed undo in Julius so hopefully I got your problem fixed. Obviously the fix needs to be merged to Augustus, but to prevent issue crowding I'm closing this for now.
