### ISSUE TITLE
Retirement age ideas

### ISSUE THREAD

**Issue by onurarpapay** [Keriew/augustus#170]
I know that you can set up retirement age to some extent on the main configuration menu, but I think game could give the governors more options for setting the retirement age without leaving the city and changing in the main menu. Some ideas:

1) Governors can decide retirement age of their city within the advisor's panel (perhaps after surpassing a population milestone like 500). It can have a upper and lower limit, like lower limit of 40 or 50 and upper limit of 65 or 67 (hail to fellow Germans out there). 
2) Upper age limit for retirement may be related to the overall city health. I.e. in a city with perfect health, governor could set a retirement age of 65, whereas a city with poor health cannot employ anyone over age of 40. Just an idea.
3) Currently, hospitals are not needed to raise the level of city health if you have enough clinics and bath houses. They are only needed by patricians, which makes the hospitals unnecessary to some extent. As an idea, to raise the retirement age over 50, certain hospital coverage might be required by the game. I.e. for retirement age of 55 you would need average/good coverage, for 60 good/excellent coverage, for 65 excellent/perfect coverage. Let's make hospitals great again! :)

This will give the governors more freedom over control of their workforce. To mitigate the possibility that one can set the retirement age to too low so that unemployment is not a problem, game can still calculate unemployment as if retirement age is 50, or the minimum retirement age of 50 can never changed (despite my suggestion in item 2, to decrease complexity of introducing a new gameplay element).

**Comment by arkimedes1967** [comment]
I agree with you to some extent but not entirelly about the governor decision of the citizens working age. It might makes sense if you take into account the productivity issue: a working citizen of 60 years (because you/governor decided so) wont produce as much as a 18 years worker. So, if the average working age on your city is to high, it should affect the producivity of your city, it means less commodities produced even with full staffed industry.

I agree with the hospital opinion, though. I even remember having suggested the inclusion of the Disease on Risks overlay.

**Comment by cdsmith-umn** [comment]
I know that the developers are planning to change how health is calculated to make hospitals more relevant. I don't know when that will happen, as I know they have other priorities right now.

**Comment by onurarpapay** [comment]
> I agree with you to some extent but not entirelly about the governor decision of the citizens working age. It might makes sense if you take into account the productivity issue: a working citizen of 60 years (because you/governor decided so) wont produce as much as a 18 years worker. So, if the average working age on your city is to high, it should affect the producivity of your city, it means less commodities produced even with full staffed industry.
> 
> I agree with the hospital opinion, though. I even remember having suggested the inclusion of the Disease on Risks overlay.

60 years is not that old in fact. Yes they are not as dynamic as 18 year old worker, but they could outweigh this by their experience. I disagree that only age is a determining factor for worker output.

**Comment by cdsmith-umn** [comment]
> > I agree with you to some extent but not entirelly about the governor decision of the citizens working age. It might makes sense if you take into account the productivity issue: a working citizen of 60 years (because you/governor decided so) wont produce as much as a 18 years worker. So, if the average working age on your city is to high, it should affect the producivity of your city, it means less commodities produced even with full staffed industry.
> > I agree with the hospital opinion, though. I even remember having suggested the inclusion of the Disease on Risks overlay.
> 
> 60 years is not that old in fact. Yes they are not as dynamic as 18 year old worker, but they could outweigh this by their experience. I disagree that only age is a determining factor for worker output.

I am quoting your reply, @onurarpapay, even though you are not the one who suggested changing productivity. I feel like varying productivity is getting to the point where variability, nuance, and "realism" crosses the line into being onerous for most players. If I have to start dealing with stuff like that, then I would just rather not play the game at all. To be honest, I am already feeling a bit overwhelmed with trying to figure out how to afford the new monuments and getting them built in a reasonable amount of time. So much so that I have not even played the game in the last two or three weeks - and that's playing on "normal".

**Comment by cdsmith-umn** [comment]
> I stopped playing C3 because it was too easy, even on very hard mode. It's not difficult to make money if you plan your city carefully. you might doing something wrong, or too quickly. It requires time and pacience...

Well, not everyone is a Caesar 3 deity like you. Also, I don't play this game to take four real life days to complete a scenario. I play it for an enjoyable diversion that takes up three or four hours once a week. My problem is I am unable to balance the need to grow the population, provide defense, provide food, and get industry going to pay the bills.

**Comment by arkimedes1967** [comment]
> My problem is I am unable to balance the need to grow the population, provide defense, provide food, and get industry going to pay the bills.

We are going off the topic, sorry. I play C3 more or less the same hours then you. If you need some tips to run your city, please mail me: arkimedes 1967@gmail.com

**Comment by crudelios** [comment]
Since this is a discussion rather than an actual issue, I'm closing this.

Feel free to continue the conversation in the `Discussions` page.
