### ISSUE TITLE
Some bugs and ideas

### ISSUE THREAD

**Issue by FalangerSeich** [Keriew/augustus#171]
Ask your question here.
Hello!
I have some ideas and bugs.

1. Houses must have manual adjustments for every goods stockpile quantity. This will be useful to prevent first houses near market to "suck-off" all market lady's capacity, and also, to limit level of house.
2. On maps with natives, must be trade option, like with imperial cities. Now we have strange thing: after missionaries convinced natives to be loyal, they buy SOMETHING from you, and you don't know, what do they want and how much.
3. I think, Colosseum should be much bigger and the only one per map, like hippodrome.
4. Granaries and warehouses still have strange behavior on long distances: always the nearest to farm/workshop is chosen! I think, it must be priorities for granaries and warehouses, or direct chaining "producer-taker" option. Direct chaining will be also VERY useful in cities, which are able to sell food.
5. Would be useful to create hunting and domesticating mechanics in future. Something like Hunting Lodge to hunt sheep/zebra/wolves for food, later something like upgrade to domesticating, to create combat dogs for military purposes, domestic horses, (invent something for sheep, or rework them into cows, e.g.) Or just add many new species. May be also one new branch for domesticating: "automatization" with animals: fast-moving carts yoked with bulls  (domesticated male cattles are STILL being in use everywhere in the world :-) ), fast-moving prefects on horses, UNLOCK for cavalry option; horses, bulls and donkeys on farms (decreasing human personnel and improving efficiency very much)
6. Would be a very good idea to create zoo in 2 variants: small and Grand, or just one Zoo per city. And it will unlock Lavish Gift to Emperor. Now we have an option: gift to Caesar giraffes and other animals, it would be much better and much more logical to create Zoo at first, buy animals to it, then get the possibility to give a gift to Caesar.
7. Please, not overwhelm with levies: it is good idea in general, but it must NOT be created for all structures. I think, it wold be logical add levies for unique entertainment structures, like Hippodrome (and Colosseum, Zoo, etc, if you will rework them to Unique and add Zoo), for all educational structures (it is logical to pay for keeping education "on the edge") and that's all.
8. Now Grand Temples and Divine Powers they grant are useless: they take tooooooo long time to build, even if you have  enough materials, and their powers are too small to be of any use. Coefficients must be much better, or, at least, human-adjustable, like some original Caesar-3 params in file C3_model.txt. In current game mechanics, 10%-20% are nothing worth to contribute in. It must be 50%+. Also, must be some divine powers to grant some kind of food and goods to houses, e.g. "Ceres grants food for all houses", and food of 4th, unused on map type, is generated in houses, or just a wheat, "Poseidon's temple acts as reservoir AND fountain", etc... Grand temples must share some USEFUL power map-wide, and have some 1-2 USEFUL powers in range of it, or in passage of priests of that god
9. Wil be an extremely interesting if it would be implemented divine synergies - 1-2 additional "wonderful things" for each combination of 2 Grand Temples and 1-2 for each Epithets on them.
10. All educational and entertainment structures need to be reworked to educate/entertain many more people. Now we need just to place abundant quantity of each structure on map to fullfill all needs. Maybe, rework in way of current medicine implementation is needed: 1-square structure just to maintain level of service, large - to improve an to serve many people. e.g., small basic school to set marker "education exists in this district" and give 1 point of education, then large School, 1-square artist-stage ON ROAD, like in "Pharaoh" and theaters, amphitheaters, etc...
11. Small and large temples must be reworked in way to stop forcing player place all the five of them per each ~500 people of population. This is very silly and useless.

**Comment by cdsmith-umn** [comment]
3. The Colosseum is already due to get changes in the near future. They will be changing how entertainment (and probably religion and education - but don't quote me on that part) is calculated.

4. Granaries and warehouses get foods and goods from the nearest building that has the food or good the cart pusher is trying to get **and** which is not set to "get".

1. I don't see this as being very useful. I also cannot imagine how much effort this would take, as it would require UI changes and variables to track each individual house's settings. Clever use of roadblocks, market special orders, and granary & warehouse special orders will give you most of the control that you really need in this regard.

2. As far as I have observed (and someone can correct me if I am wrong), natives tend to buy whatever you have available for trade. They work like cities: If you have it available to sell and have set the Trade Advisor to export it, then they will buy some. If you have the Trade Advisor set to **not** export a good or food, then no one will buy it. Here again, I would think implementing this would require a fair amount of work since it is going to require UI changes and changes to the logic to treat the natives as though they are a foreign city.

**Comment by FalangerSeich** [comment]
2. Why not use "Empire boundaries have changed" for natives?
4. I know this fact. But supplying food is still buggy.

**Comment by cdsmith-umn** [comment]
Based on my interpretation of what you are asking for when it comes to changing how granaries and warehouses work, that would be an incredible amount of work. The UI would have to change, which has already been noted in other places as difficult right now, to facilitate the player being able to specify which other granary or warehouse should be the source. This means there has to be a way to list out all the granaries or warehouses (as appropriate) and there has to be a way for the player to name each one. Without the ability to name them, they will all just show up as "Granary" or "Granary X" (where "X" is an integer).

The other way this could be done is to be able to click on a specific granary or warehouse on the map, which is a whole other mess of UI and logic changes.

If the "primary source" granary or warehouse has nothing, then the cart pusher still comes back empty. That will then create the request to set a "secondary" set of logic to govern where the cart pusher goes from there.

Probably the easiest way to accommodate something like this is to be able to set a granary or warehouse as being able to be perceived by other similar structures as "accepting" even if it is set to "getting". That would enable you to set up "feeder" buildings that get the selected food or good and make it available to be retrieved by other nearby "getting" buildings. Even if they made this change in this way, food availability could still be difficult sometimes.

As for your additional suggestion of domesticating and/or hunting animals, I don't really have any thoughts on this. It is an interesting idea and, to my mind, would require the map to generate more wild versions of the animals in order to make the use of the relevant new structure worthwhile. Sheep would not have to be made into cows; they are plenty useful and edible as sheep. :)

**Comment by sickchicken** [comment]
8.In some maps, missions are usually done before we finish any Grand Temples, unlike Emperor : Rise of the Middle Kingdom. (Oh, yes. they have plenty of time before we clear any mission in Pharaoh or Emperor) We can barely see those only in late missions. We could use some cheaper and quickly built Grand Temples. Also, I don't think some Grand temples are worth building. Like, who the hell wants Mars Ultor? They are big, expensive, hard to build but some Grand Temples are just not worth it.
7/11. Temple are built in large numbers, and its levies are quite expensive. Perhaps they can cover more population and offer more bonuses, if they cost that much money.

**Comment by Legionary2** [comment]
Domesticating is interesting as I have been thinking about this among the dev team too. I don't know if I would complicate it with having to "catch" and harvest the animals so to speak. But I do find livestock as a useable resource for transportation upgrade methods very interesting.

**Comment by Areldir** [comment]
Ok, to address the points on Grand Temples. We've reduced resource requirements for them across the board in the release branch, so its less of a drain. Still, having played far too many scenarios with them during testing, I don't actually find them to be a late game issue. If you rush them correctly, you can easily have at least 1 Grand Temple built in the first 10 in-game years of a particular scenario. Furthermore, we can continue to tweak the bonuses according to testing results. If you have specific suggestions for any of the bonuses, feel free to share.

**Comment by crudelios** [comment]
This conversation is better for discussions, not issues, since they are not really issues but ideas.

Therefore I'm closing this. Feel free to continue this conversation in the `Discussions` page.
