### ISSUE TITLE
Market buyers cannot collect from any granary with available stock

### ISSUE THREAD

**Issue by klei1984** [Keriew/augustus#177]
Describe the bug, the steps to reproduce, and if possible attach a saved game that show the wrong behavior and augustus.ini file to show which options are being used.
[save_ini.zip](https://github.com/Keriew/augustus/files/5726391/save_ini.zip)

Game version is latest windows release, v2.0.1. After a couple hours of game play and about 1700 happy citizens I started to notice devolving housings and could not figure out the reason. Finally I realized that none of the market buyers reach back to the markets. The buyers reach the granaries, but they simply disappear instead of reappearing with granary boys. The gameplay_change_global_labour setting was on, but in the attached augustus.ini it is disabled. No difference. Tried delete, recreate many of the buildings, changed the roads, blockers and lots of other things to no avail. Checked with latest unstable build as well, no difference.

Finally I realized that the leftmost granary had 32 wheat. Not 32x 100, but really 32. Wheat is not even producible on this map. Deleting this single granary and getting rid of the 32 wheat eliminated the issue globally. Emptying the offending granary also resolves the issue without deleting it.

**Comment by crudelios** [comment]
Have you deleted a stocked warehouse and/or used undo?

**Comment by klei1984** [comment]
I am 100% sure that I did not use undo. I never use it.
I am not so sure about the warehouse. I do not think that I deleted one. What I can recollect is that Mars was angry and an army attacked the city. Maybe a warehouse did destroy in the event, but this is just a guess, I spent like an hour to figure out what was going on.

**Comment by crudelios** [comment]
@Keriew @bvschaik I found the source of the bug, you'll like this one.

If you have an active amphitheater and a gladiator school, the gladiator school will spawn a gladiator which gets to the amphitheater.

If, during the trip of the gladiator to the amphitheater, you delete the amphitheater and replace it with a granary, the gladiator, upon arriving at the amphitheater, will add "32 days of entertainment". But since the building is now a granary, the memory address will be that of the "amount of stored grain". Hence the mysterious 32 grain added to the granary.

Note that this only happens if there was no earlier free building slot in memory to place the granary.

This bug also happens in Julius but curiously enough it doesn't happen on original C3.

**Comment by bvschaik** [comment]
It doesn't (appear to) happen in C3 because the memory layout for those extra fields is different in Julius... in C3 the "32 entertainment days" would be written at byte 28 of the "type data" in the building slot, which for granaries would correspond to "32 weapons" which of course cannot be stored in a granary. Nice one indeed!
