### ISSUE TITLE
Suggestion: Music & City Sounds Stops With Game's Inactivity

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#181]
Like most of modern games, it goes to stand-by mod after more then 10 minutes of game's inactivity.

This means, no music and no city sounds till the game is unpause OR the player restarts the game again. I'm pretty sure of it in CotNile but not so sure about the subsequent impressions games.

**Comment by arkimedes1967** [comment]
What i'm suggesting is not so intrusive such mutting the game imediatly when pausing the game, that i'm deprehending from this [PR](https://github.com/bvschaik/julius/pull/538).

What i'm suggesting is:  

- If player pauses the game **or**;
- If the game stops when a popup massage is shown and player do not dispatched it;

**for at least the next 10 minutes**, we can surelly conclude that **player leaved the game**. City sounds and music then should stop (**fade out**).

If the game is unpaused or the message dispatched, then the game restarts again and the music and sounds return (**fade in**).

**Comment by crudelios** [comment]
Why should we add this?

I don't see this serving any useful purpose really.

**Comment by arkimedes1967** [comment]
Nevermind, but you've changed your opinion since the last time.

It's just a suggestion, and the last one i do, believe me.

You may close this thread.

**Comment by crudelios** [comment]
Well, I do think this goes beyond the scope of the game, and would require adding timers and constantly updating them/checkong for input just for a small eye-candy that many people wouldn't even discover.

Since no one else expressed an opinion on this, I guess there is no general interest in this feature (if there was, it might be added).

Therefore I'm closing this.
