### ISSUE TITLE
Add option in the options menu to allow building more than 2 Grand Temples 

### ISSUE THREAD

**Issue by TheChymera** [Keriew/augustus#189]
It would be cool if a city could have more than two (i.e. all) grand temples. Would it be possible to add such an optional feature?

I have tried a ham-fisted patch here (https://github.com/TheChymera/augustus/commit/0848f01a29f93b1a4a6048d497284498233fd53e — not for the option in the menu, but just hard-coding a higher limit), and it seems to work in as far as it doesn't cause any further complications in the gameplay (or none which I have yet noticed).

**Comment by crudelios** [comment]
There should be no side effects to adding more temples in the code, however for a gameplay perspective we settled with allowing only two.

**Comment by TheChymera** [comment]
@crudelios yes, it does give the gameplay an interesting artificial constraint which can make choices feel more significant, but the options already give a lot of leeway for leisurely playthrough with respect to other things, such as increasing the worker pool, adding more forts, etc. I think it would make sense to have a separate option for people looking to build a “maxed out” city on one of the later missions.

In any case, I just finished Massilia using my patched code, with a grand temple to each god, so it certainly works other than the constraint introduced in those 3 places.

**Comment by crudelios** [comment]
Since this is a gameplay setting on which we'll base future balance updates (including new scenarios and whatnot), I think we shouldn't have this even as an option.

@TheChymera like you did, anyone can change the source code to support more grand temples. That's the beauty of open source 😉 

Since no one else commented here I think there's no general desire from other developers or users to thange this, so I'll be closing this issue.
