### ISSUE TITLE
Please update the Korean version.

### ISSUE THREAD

**Issue by sickchicken** [Keriew/augustus#232]
We already finished the translation and update of the fonts, but file's still older version and there are Korean players & streamers saying it's annoying. It hurts since we did our job. Please update the file and the link.

https://github.com/bvschaik/julius/wiki/patches

And this is KR readme file for people having trouble with it.
[patch_readme_KR.txt](https://github.com/Keriew/augustus/files/5948356/patch_readme_KR.txt)

**Comment by crudelios** [comment]
@sickchicken I may be missing something.

You did create a PR that has already been added and is available on the unstable version.

That link to the patches has nothing to do with it. Is something missing from there?

**Comment by sickchicken** [comment]
Did not check the translation issue, sorry for any inconvenience.
https://github.com/Keriew/augustus/issues/183
But I fixed/made a Korean font set myself and that's not updated yet. It would be great help if you update this font for me. 

P.S. For some unknown reason, font problem is kinda gone in latest version. I found my Korean texts basically not readable at all last December, but now I think I do. Back then, (like you see in bvchaik's screenshots) most of Hangul characters had couple of their lines completely gone.
But just to make sure that doesn't happen again, I still want to change it from Sans-serif into Serif. They mostly used Serif font in retro game for readability issue. In Korean version, it's all Sans-serif.

**Comment by crudelios** [comment]
Humm, so you mean the new fonts haven't been added? These ones? [korean_new_fonts_2.zip](https://github.com/Keriew/augustus/files/5747277/korean_new_fonts_2.zip)

@bvschaik, did you end up updating that `555` file in the patch?

Also @sickchicken, the translation is probably on the `unstable` version that can be downloaded, but not on the `release` version as there hasn't been a new release since you added the new translated strings. In fact there probably already are some new strings in need of translation on the latest `unstable`...

**Comment by bvschaik** [comment]
No, I didn't make time for it yet.

I just updated the patch file with the new fonts, and with the updated readme, thanks for translating that.

**Comment by crudelios** [comment]
Thanks, Bianca!

I think that's all, so I'm closing this. Let me know if I missed something please, sickchicken.
