### ISSUE TITLE
Markets and Docks list unavailable commodities

### ISSUE THREAD

**Issue by Riww** [Keriew/augustus#243]
...while Warehouses and Granaries don't. For example in campaign Tarsus, fruit, vegetables, and vines are not available by any means. They should not be listed in Special orders for Dock and Market. They are correctly not listed in Special orders for Warehouse and Granary. They are also not listed in the Trade Advisor panel. 

1. Therefore, Markets and Docks should not list unavailable commodities under Special Orders button.

2. Special order button title should be more uniform. Currently:

Granary: Granary instructions
Warehouse: Warehouse instructions
Dock: Dock
Market: Goods to collect

I suggest using "Dock instructions" and "Market instructions" for uniformity.

3. For Dock and Market, the tooltip for the "X" button is missing. It should say: "Refuse goods" as it does for Warehouse and Granary.

**Comment by crudelios** [comment]
Hi, thanks for your issue. I agree with all your suggestions, so I'll get to implement them when I have the time.

**Comment by Riww** [comment]
Also Supply Post has the same issues.

**Comment by crudelios** [comment]
Upon further thinking, I believe markets, supply posts and docks should display all importable resources, not just the ones that are already being imported.

The reasoning is so that you can control what to accept/reject even before imports are defined, otherwise you would get unwanted goods upon new imports.

Therefore I'm changing docks/markets/supply posts to display all potentially importable resources, instead of simply all of them.

**Comment by Riww** [comment]
Importable resources - of course they must be displayed! I am talking about UNAVAILABLE resources - those that already don't show up in Warehouse, Granary, and Trade Advisor, meaning they aren't available by ANY MEANS. Only those shall not be displayed.

**Comment by crudelios** [comment]
Fixed by 9e5fe3c.
