### ISSUE TITLE
Suggestion: Requests of Food from Caesar

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#28]
Please exclude this thread.

**Comment by subatron** [comment]
I disagree, Arkimedes. When you think about what Granaries are actually meant to do, they're meant for distributing to YOUR city, not others. Warehouses, much like modern day warehouses, are meant for storing and moving goods. That's one reason that it makes sense that warehouses can get from other warehouses without a road connection. 

A better suggestion would be to allow the player to specify, at the farm level, what building they attempt to deliver to first. If that building doesn't exist via road connection, then it goes by its default (so if you choose warehouse, and there isn't one, then it defaults to trying to deliver to a granary.

**Comment by arkimedes1967** [comment]
Using you own argument, farms should deliver by default to warehouses and not to the granaries. BTW, it happens to be so on Pharaoh/cleopatra.

**Comment by LordBaal** [comment]
Well, in Pharaoh the food stuff goes to fill the granaries first and then if some warehouse is receiving it then it gets it, unless the warehouse is under get which I think it has priority over granaries, unless the granaries are also on get order which then gets the priority again over warehouses. But I could be misremembering on this, even in this case it would make sense to employ something along those lines. Granaries should be filled first unless there's a warehouse you have on Get the thing, which then should be filled first and then granaries.

Just my two cents.

**Comment by arkimedes1967** [comment]
Check again @LordBaal , it goes first to warehouses even if you have enought space on granaries.

**Comment by LordBaal** [comment]
Oh, when I said I could be misremembering on this, I meant the whole paragraph. Still, something along those lines could be done to work out this issue don't you think?

**Comment by crudelios** [comment]
Maybe if some of the food came from a granary a confirmation window warning the player that some/all food would be removed from a granary could display first.

**Comment by Areldir** [comment]
Alternatively, perhaps add a button to select food to send from either granaries, warehouses, or both? Then its up to the player to choose.

**Comment by crudelios** [comment]
I'm already implementing my own idea now haha

**Comment by crudelios** [comment]
So the UI part is finally done and I need comments:

When food is being obtained from granaries and not only from warehouses, the text displays `X in storage` instead of `X in warehouses`. Hovering the button will show how much food is being obtained from warehouses and how much from granaries:

![city 2021-01-26 15 53 31](https://user-images.githubusercontent.com/6518876/105871868-a41c3080-5ff1-11eb-923a-79d5c324dea3.png)

When enough food is available from granaries, a new popup will appear alerting that your population may starve (this does not appear when all the food is being fetched from warehouses):

![city 2021-01-26 16 13 05](https://user-images.githubusercontent.com/6518876/105871947-bd24e180-5ff1-11eb-85d9-c77da9d3e276.png)

Any suggestions?

**Comment by arkimedes1967** [comment]
> Any suggestions?

Perfect!
