### ISSUE TITLE
Fonts are blurry

### ISSUE THREAD

**Issue by senner008** [Keriew/augustus#378]
The fonts look blurry compared to vanilla
<img width="251" alt="2021-05-17 15_56_01-Caesar III" src="https://user-images.githubusercontent.com/47080964/118508653-aa185780-b72f-11eb-944a-4e8f6078eac1.png">

System:
Windows 10
Augustus version 3.0 release

**Comment by crudelios** [comment]
What's your display scale?

**Comment by senner008** [comment]
100%

**Comment by senner008** [comment]
Its not only fonts it seems. How can I take screenshots in vanilla?

**Comment by crudelios** [comment]
While yours seems to be sligtly blurry, it seems to be working fine for me.

When you mention "vanilla", do you mean Julius or Caesar 3 itself?

The "full screen" option on Julius/Augustus is the same as your desktop resolution, so if your desktop resolution does not match your monitor's native resolution you would get the blur. That wouldn't happen on a widescreen C3 patch because the widescreen changes the actual desktop resolution, just like C3 did back in the day.

**Comment by senner008** [comment]
Yes, vanilla is running GOG Caesar directly. 

Ok.
I can fix it though, but setting the display scale down to 100% from 150% in the windows display settings

Is there no way for the game to override this? Outside the game I prefer larger fonts since my screen is small but high resolution


![2021-05-17 17_33_21-Settings](https://user-images.githubusercontent.com/47080964/118515917-1e55f980-b736-11eb-831d-ab6f3185a51c.png)

**Comment by crudelios** [comment]
There should be a way to override it by right-clicking the `augustus.exe` file (or a shortcut), checking the `Compatibility` tab then messing with the `DPI` options. I'm not sure how it works though and since my Windows version is not in english I can't really direct you to the proper fix.

**Comment by senner008** [comment]
Works perfectly

**Comment by crudelios** [comment]
Glad you got it working! Have fun!
