### ISSUE TITLE
Market Lady can't get food

### ISSUE THREAD

**Issue by SilverSight1** [Keriew/augustus#406]
I have a save file where the Market Ladies, (only the one's located here in the left-most town center) are stuck in a sort of loop where they go towards the granary, but then take a u-turn back around the aqueducts, thus never getting any food.

Noticed this started happening shortly after I held my first Colosseum game in the city which costs a chunk of wheat.

![Screenshot_2021-05-25_17-14-05](https://user-images.githubusercontent.com/60754559/119474093-64d2d600-bd7e-11eb-83cc-b66ad07cc4da.png)

[My Rome why.svx.zip](https://github.com/Keriew/augustus/files/6538113/My.Rome.why.svx.zip)

Using latest stable release.

**Comment by crudelios** [comment]
It's a coding oversight of mine.

Remove the gardens right above the aqueduct and the market ladies will work again.

Technical explanation for those geek enough to be interested: In the new Augustus version, the market ladies recalculate the best destination every 120 game ticks. In order for the market ladies to select a valid destination, the tile they are standing must belong to a valid network ID (meaning, it must be on a road).

Since on the current case the market ladies travelled over grass, they would recalculate the destination over an invalid road network (the grass is not part of any road network). Because of that, they would not search for any granaries and come back.

The fix is simple: only recalculate your destination if you are on a road.
