### ISSUE TITLE
Extra assets could not be loaded

### ISSUE THREAD

**Issue by Chronius1** [Keriew/augustus#463]
Ask your question here.
I downloaded the latest version of Augustus and copied it into the C3 file but when opening the game it says that the extra assets could not be loaded. I have downloaded the development assets also but it still gives me the same message whenever I open the game. 

Any help would be greatly appreciated, many thanks

**Comment by crudelios** [comment]
Hi,

Which version appears on your main menu?

Also, where did you place the assets folder? Did you unzip it?

**Comment by Chronius1** [comment]
I downloaded the version 3.0.1. for Windows on the main menu and then downloaded the development assets file, unzipped it and placed it into the C3 file which I had downloaded from Steam.

**Comment by crudelios** [comment]
Ah, so that's the problem. The development assets are for the development version of augustus and aren't compatible with v3.0.1 anymore.

You have two options:

- Download the [development version of augustus](https://augustus.josecadete.net/download/latest/development/windows) (actually recommended as it fixes some bugs and crashes of v3.0.1) or
- Download the [v3.0.1 assets](https://augustus.josecadete.net/download/latest/release/assets), delete the old assets folder (simply overwriting won't work) and copy over the downloaded assets folder.

Hope this helps!

**Comment by Chronius1** [comment]
Great, all downloaded and working perfectly. Thanks ever so much for your help.

**Comment by frase3** [comment]
I am having the same kinda problem. Downloaded the newest unstable build, seemed to go ok had all new buildings and ui everything until I noticed my architects gobbling up resources and no monument construction was happening.  So went back tried a combination of downloads to see which assists (I’ll get to that struggle in a minute) we’re goin to work on the map I was playing can’t remember which from Caesar heaven but downloaded new 08/08/23.  Wound up taking all my map files out of Caesar 3 file and deleting/reinstalling game from gog tried the 3.2 version got the assets message (on a map most likely built for unstable version) tries a different older map still no architect working.  Maybe a bug still but thinking have to start from scratch again with original Augustus original maps, download updates chronologically maybe stay away from
Unstable build until next time.  Any help would be appreciated for a c3 lover.

**Comment by crudelios** [comment]
@frase3 If you have discord you should join the zakh's server and ask for help there, you'd probably have a more immediate answer and help.
