### ISSUE TITLE
Issue with market buyer and warehouses.

### ISSUE THREAD

**Issue by Purakane** [Keriew/augustus#486]
I'm running the latest version of augustus and I'm noticing the following issues. I'm not sure if anyone else has  but it ruins the game as everything starts to collapse after hours of building.

-market buyers and warehouses will have good brought in but when you right click on the building, the goods show as 0.
this typically happens in mid-late game when population is over 6000. A 9x9 will eventually devolve due to lack of food/pottery.

-Unable to build large temples inside of 9x9's even with a warehouse full of wood, clay, marble right outside and a workshop both outside and with in the 9x9. I even went as far as testing it by removing the roadblocks and still nothing happens.

**Comment by crudelios** [comment]
Can you leave a savegame, please?

**Comment by Purakane** [comment]
[level 11D.zip](https://github.com/Keriew/augustus/files/7182047/level.11D.zip)

thank you

**Comment by crudelios** [comment]
Regarding the markets, it is a logistics issue. You have too few vegetable farms on the south side and no granary getting vegetables on the south. The market ladies need to go far away to fetch vegetables, thus having no time to fetch meat or other goods.

At the same time, because the houses have no vegetables, even large amounts of vegetables, like 800, get used up by the houses instantly. Indeed if you slow the game down you'll notice that the market does register the vegetables, but a few in-game ticks later the vegetables have been distributed.

To make things more stable, you should get one of the southern granaries (or even both) to getting vegetables while still accepting meat.

Also, specialize the markets. One for food and one for goods is enough to keep a block stable.

Regarding the monument issue, there was a bug on 3.0.1 that has been fixed. That may be the issue. We'll be releasing v3.1 soon which should fix it.

**Comment by crudelios** [comment]
We have recently improved food consumption of houses which should hopefully fix these sorts of issues.

Either way, I'm closing this issue as I think all the reported bugs have been fixed.
