### ISSUE TITLE
Ability to change game speed when a dialog is present

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#51]
If it's possible, it would be a welcome change to be able to change the speed of the game when there is a dialog notification on the screen. Specifically, this would be the most beneficial when you receive a notification that your city is being attacked. I would like to be able to change the game speed before dismissing the notification, which would maximize the time I have available to move my forces around. Alternatively, if there is some way to "pause" the game even after the dialog is dismissed, that would be functionally the same. It's also possible that I just don't know how to do this and the game is already capable of this.

**Comment by arkimedes1967** [comment]
Try to do as follow:

- When the dialog appers, click on the "go to the problem area". Now you know where to send your trrops;

![Local Uprising](https://user-images.githubusercontent.com/64329357/83908461-125c6c00-a75f-11ea-83bf-736d27e25eb3.jpg)

- Dismiss the dialog right-clicking on the map;
- Pause the game;
- Reduce the game speed to 50%;
- Use the radar-map to reach faster to your troop forts;
- With the game still paused, click on a fort (a sword apear as mouse point) and then click the local of the map you wish to defend. You may use the radar-map also, because the sword will remain active;
- Repete the process to your remaining troops. You can only ear the troops mooving sound but not the banner, don't worry;
- Unpause the game;
- Rearrenge your troops. I've pre-marked lines to ensure they facing the enemy: the closest line to the wall is the call-line;

![Troops display](https://user-images.githubusercontent.com/64329357/83908608-50f22680-a75f-11ea-8333-ebc568802f42.jpg)

![troops on first Line](https://user-images.githubusercontent.com/64329357/83908622-58193480-a75f-11ea-8f7f-5fe007d082c0.jpg)

- Moove your troops to the second line only after they arrive & stay still on the first line. 

![troops on Second line](https://user-images.githubusercontent.com/64329357/83908641-5fd8d900-a75f-11ea-8249-41b1038fd36d.jpg)

**Comment by arkimedes1967** [comment]
Personally, and to make the game more interesting on Very Hard mode, we **shouldn't** be allowed to do **during battles**:

- Build military buildings;
- Pause the game;
- Reduce the game speed

**Comment by cdsmith-umn** [comment]
Thanks. That helped me a lot. In 20 years of owning and playing this game, I never realized that pressing "P" paused the game.
