### ISSUE TITLE
Request: Unlock All the Campaign Missions

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#59]
I realise that we can't play all the missions of the campaign because some of them (10) aren't available on the Caesar 3 Construction Kit:

- Miletus, Tarsus, Massilia, Brundisium, Tarentum, Syracusae, Tingis, Lutetia, Damascus and Sarmizegetuza;

**Is it possible to unlock them?**

**Comment by Keriew** [comment]
Hey, thanks for the report.

There are multiple matters here, and I'd appreciate if in the future you could open a separate issue for each of them. That makes it easier for me to track what's done and what's yet to be done.

City construction kit maps are different from career maps - career Lugdunum is different from CCK Lugdunum, so you can't really play career Lugdunum with CCK unless someone redid that map in the editor. Adding the career maps to CCK also wouldn't be trivial, because they are stored as saves and not as .map files. I'll think of a level selection screen for the career in the future.



As for the trade errors in the career, I agree that it'd be good to fix that. I'll get around to it.


Third issue being the game being too easy, I agree that some modifications would be helpful here, especially considering that most Augustus changes make the game easier. I'd like to keep the career maps as they, but I've thought about the possibility of adding an extra difficulty level for veterans and maybe have that difficulty level affect more things than those already in C3. If you have any suggestions or ideas for that, please open an issue for it.

**Comment by arkimedes1967** [comment]
> There are multiple matters here, and I'd appreciate if in the future you could open a separate issue for each of them. That makes it easier for me to track what's done and what's yet to be done.

I'll edit my post in 3 separate threads as requested right away.

**Comment by crudelios** [comment]
Regarding unlocking all the carreer missions: You can cheat a victory and get a savefile with a new career mission map.

I think the remaining reported issues are resolved, so I'm closing this.
