### ISSUE TITLE
Request: Add an Extra Difficulty Level for Veterans

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#61]
Please exclude this thread.

**Comment by pavel-klavik** [comment]
Adding these changes would just make playing more annoying, not more difficult. I can already finish the game without using most of the things you suggest removing. For instance if you are building something during the invasion, you are already doing it wrong. Roman soldiers and battle tactics were OP, otherwise they would not be able to expand.

I would support a greater difficulty level for increasing the requirements, making larger attacks, more requests from Caesar, etc. For instance, double the population requirements on each map. Then fitting all the population there is a chalange, balancing which house blocks gets imports and which do not, etc. There is no reason why Valencia not require 20k people there.

**Comment by Riww** [comment]
Better add a new "Veteran" difficulty which would just scale from Very Hard, nothing extra, because really, Very Hard is not actually that hard. For Veteran I suggest: starting and rescue funds: 50%, starting favor: 30, city sentiment: 30 (maybe leave that at 40 or 35 to make sure people come to empty lots at start), invasion numbers: 140%, levies: 150%, food consumed per soldier and month: 6.

**Comment by crudelios** [comment]
Adding an extra difficulty level has been considered.

However, since this is a suggestion more than an issue, I'll be closing this. Feel free to discuss it on discord or the forums!
