### ISSUE TITLE
pottery workshops stop taking clay

### ISSUE THREAD

**Issue by greggman1221** [Keriew/augustus#619]
Had a strange situation today in Carthago. out of nowhere, all pottery workshops in the city simply stopped getting clay from the warehouse. there is an empty warehouse for pottery, a full warehouse stuffed with clay, and plenty of employment. any ideas? same issue with furniture workshops, next to warehouses full of timber.
killing all imports of weapons solved the problem, but i'm not sure exactly why.
also: for some reason i'm able to import 100+ clay, where I think it should change to 'import max' at some point.
Thank you!

**Comment by Keriew** [comment]
Do you have a save with this issue? It would help investigate the problem.

**Comment by greggman1221** [comment]
Sure! Here you go. Take a look at the pottery workshop alone by itself, in the far left of the city (near the mission post).
It has full employment, as does the warehouse right next to it (which is loaded with clay).
But, the pottery workshop never gets any clay.
I am not sure why not! Here's the sav:
[testbug.zip](https://github.com/Keriew/augustus/files/8864854/testbug.zip)

**Comment by greggman1221** [comment]
I think what is happening is the warehouse cart is preoccupied going across the city to fulfill a request from a workshop across the map, rather than the workshop right next to it.. Switching the adjacent warehouse to 'getting clay' allows it to supply the workshop right away!

**Comment by crudelios** [comment]
The problem you have is a logistical issue.

You have two warehouses accepting clay: one next to the sea, and another one further inwards.

Clay seems to be imported to the inwards warehouse. Timber is also imported to that same warehouse.

Looking at the industries, there is a single workshop close to that warehouse. All the other pottery and furniture workshops are far away.

What happens is that the cartpusher is always busy trying to meet the timber demand for the furniture workshops. Due to the distance, it can't handle even that. So the pottery workshops never get clay.

Also, the warehouse close to the sea doesn't have any room for clay. Even though there are some free spaces, every warehouse "square" can only accept a single type of good. Every square has at least one good, and no clay. So clay won't get distributed there.

As you mentioned, setting a warehouse to get clay will improve the issue. Another thing you can do is avoid having a single warehouse supply two different types of industries.

**Comment by crudelios** [comment]
Sure thing, have fun! C3 has these logistical oddities that are a pain to solve but are very satisfying when your planning works.
