### ISSUE TITLE
Assets error in vita version

### ISSUE THREAD

**Issue by Zolrex** [Keriew/augustus#642]
Hi!

tried latest version build for vita,and when launching game,it giving error "could not find assets folder" but it's there (game works fine),pc version of port don't have this error.

**Comment by crudelios** [comment]
Hi,

I'll need to check this myself, but while I don't have my Vita at hand, please let me know:

- what version of augustus are you running;
- if you manually copied the `assets` folder to the C3 dir (you shouldn't).

Thanks!

**Comment by Zolrex** [comment]
> Hi,
> 
> I'll need to check this myself, but while I don't have my Vita at hand, please let me know:
> 
> * what version of augustus are you running;
> * if you manually copied the `assets` folder to the C3 dir (you shouldn't).
> 
> Thanks!
> 
> Edit: I just confirmed and the latest unstable works fine.

Yeah checked it,latest unstable don't give any error,and seems seems it's even working faster (especially in UI).
unstable seems not need assets,and when i tried to put assets folder it's crashing.
So best solution for vita for now,launch unstable release,without any assets folder.

**Comment by crudelios** [comment]
Yes, the latest version uses hardware rendering which makes things much faster for vita. However, vram usage is an issue, so assets had to be optimised to avoid crashing due to lack of vram.

Also, the "unstable" version is very close to release, so it should actually be more stable than v3.1.0 now.

**Comment by Zolrex** [comment]
> Yes, the latest version uses hardware rendering which makes things much faster for vita. However, vram usage is an issue, so assets had to be optimised to avoid crashing due to lack of vram.
> 
> Also, the "unstable" version is very close to release, so it should actually be more stable than v3.1.0 now.

Wow Nice...thanks for your great port,for a great game ) Even consider that,vita is old hardaware,it's still awesome solution to play on go with buttons control.
And next "final" version won't need assets folder too?

**Comment by crudelios** [comment]
Exactly, no new version will ever need the `assets` folder because the folder is now automatically bundled in the app.

Have fun playing the game! Let me know if you have any crashes. Do save often and enable autosave to avoid issues, as the vram limit can sometimes be reached and in that case it will crash.
