### ISSUE TITLE
Roadblock ignoring special orders

### ISSUE THREAD

**Issue by FalangerSeich** [Keriew/augustus#701]
I am playing the most recent Stable build of Augustus.
Here is save of Aedile's peaceful mission in campaign.
[ae-new-3-rb-error.zip](https://github.com/Keriew/augustus/files/9639373/ae-new-3-rb-error.zip)
I built hospital, opposite to it - doctor, near doctor - engineer, praefect. I placed orders to roadblocks Naturally: engineer and praefect must pass through 2 RBs at them, service both med buildings and houses, medics must not spawn and travel backwards the houses. But instead, all 4 structures shows "not adjacent to the road", and my buildings burns and collapses and getting infestations.

**Comment by crudelios** [comment]
This is not a bug, this is by design.

You must leave at least one road tile directly beside a building to make it spawn people.

In your case, all of them are completely enclosed by roadblocks, so they can't spawn anyone.

Roadblock orders only work for walkers that already exist, not for the ones being spawned. This allows you to control the exact spawn point by placing roadblocks around a building where you don't want its walker to appear.

**Comment by FalangerSeich** [comment]
that's so bad, but ... OK, design is design. Please, include it to next manual.
