### ISSUE TITLE
Strange bug with Warehouses

### ISSUE THREAD

**Issue by ArtySh0ck** [Keriew/augustus#76]
here is savefile with bug. i saved it in location where bug is appeared

info:
have one warehouse near to red arrow that accepts clay from marchants (import), and have another 3 warehouses (located in savefile) with getting clay option. and this all works fine till one moment. when guys took last piece of clay on "main" warehouse and brings it here, all of these 3 warehouses didnt start to give out clay to potteries, and if u look there for a some time you will some blinkin npcs near to each of these 3 warehouses. they blinks and disappear, and again and again. and no pottery as result... 

thanks!

i tried this with 1.4.1a, and 1.4.1-unstable ... no metter

**Comment by ArtySh0ck** [comment]
[BugWithWarehousesWithClay.zip](https://github.com/Keriew/augustus/files/4756318/BugWithWarehousesWithClay.zip)

**Comment by Keriew** [comment]
Thanks for the report!

Fixed with 50a1953 should be working with the new unstable.

**Comment by ariep** [comment]
I seem to have a very similar problem, so adding it here. Situation: large map (Tarsus) with distant city parts, importing clay, trying to make pottery. All pottery workshops are near a warehouse that has clay most of the time, either because it's next to the dock or is set to "Getting goods" for clay. All pottery workshops have problems getting their clay, even when their nearest warehouse contains several units of clay. Sometimes a few workshops get clay somewhere and work for a little while, but later they turn inactive again.

Given the size of the city it's possible that the workshops' cart pushers are often getting their clay from very far away, but I've observed the map for a while and didn't see clay being pushed around over long distances.

I tried both 1.4.1A (with which I first started playing this level) and also with 2.0.1 with the old savegame.

Please let me know if you need more specific info or a savegame file.
