### ISSUE TITLE
Is multiplayer possible?

### ISSUE THREAD

**Issue by WeebNetsu** [Keriew/augustus#806]
One thing my family and I have always wanted, was to play Caesar together, would multiplayer (LAN, not necessarily online) ever be possible? Where 2 people can build a city together from 2 different devices? It would truly be next level. 

I did read what the first user replied with in this thread: https://groups.google.com/g/comp.sys.ibm.pc.games.strategic/c/mUEq9FBSVl0?pli=1 but I disagree, I'd rather have the feature and not use it than want the feature but can't use it, and in this scenario, I believe many would agree, that optional multiplayer would be amazing.

**Comment by crudelios** [comment]
Hi!

We don't have any plans for multiplayer support.

Adding such a feature, while technically possible, would require a major rewrite of the entire game engine in order to support multiple inputs at once, not to mention synching the whole thing across different computers.

That would require time and effort that we feel we should devote to other new features.

However, since this is an open source project, we would welcome anyone who would be interested in adding such support. However, I think I can speak for all current devs when I say none of us are interested in adding such a feature ourselves.
