### ISSUE TITLE
Markets buggy in lastest unstable ?

### ISSUE THREAD

**Issue by soapyapi** [Keriew/augustus#901]
Running latest unstable build on map Lutetia; markets seems incredibly buggy. Food gathering erratic; no pottery at all. Runs fine in stable though. Any change made recently ? Could also be a storage bug (market unable to retrieve goods). Anyone else ?

**Comment by crudelios** [comment]
Can you post your save please?

**Comment by soapyapi** [comment]
[markets_pb.zip](https://github.com/Keriew/augustus/files/11782026/markets_pb.zip)

**Comment by crudelios** [comment]
I se the issue, you're trying to provide 3 food types without specialising your markets.

Markets always prioritise fetching food in a specific order (wheat, vegetables, fruit, meat) so if they are missing any of those foods and can find it, they'll  go for it instead of other goods.

My suggestion would be, if you really want to keep the 3 food types, get a third market per block and let each one specialise (only trade) a single food and good (so one wheat and pottery, another fruit and furniture and another meat and oil). That'll make things more stable.

**Comment by soapyapi** [comment]
Oh thanks for your input. Didn't know that. How about the pottery issue. Could you get it delivered on my save ?

**Comment by soapyapi** [comment]
Gameplay issue - not a bug. See crudelios explanations.

**Comment by crudelios** [comment]
Glad you had your issue fixed!

Market specialisation is one of the most glaring missing features of the original C3. That option makes things much smoother to manage.
