### ISSUE TITLE
Meat is always fish, but only in custom maps.

### ISSUE THREAD

**Issue by MollyRenata** [Keriew/augustus#979]
I've been playing the most recent release (not the unstable versions) for a while now, and I noticed a problem with custom maps - this strangely does not apply to the campaign.

When I make a custom map, even if I'm in an inland city with no access to fishing, meat will always have the "fish" icon and will be displayed as such in carts as well. It's a little annoying and immersion-breaking.

![meatfish](https://github.com/Keriew/augustus/assets/147318696/eb853a7e-eb0c-462c-8651-f5f52593d913)
![meatfish2](https://github.com/Keriew/augustus/assets/147318696/b95a78b4-944d-4cdb-b11e-3fd431596a3d)
![meatfish3](https://github.com/Keriew/augustus/assets/147318696/da5d6ca2-93e9-402e-9caa-9aab53564978)

Images provided as examples (test city I whipped up specifically for this purpose, based in Mediolanum, which does not allow fishing)

By contrast, image taken from a peaceful campaign mission (Tarraco), again specifically for this purpose:
![meatnotfish](https://github.com/Keriew/augustus/assets/147318696/03796e98-1f0d-4c93-9af2-982f3833ee81)
As you can see, the meat is not fish here.

**Comment by Keriew** [comment]
The way it worked in base Caesar 3 and stable version of Augustus is: if you have wharf available during a mission, the meat is displayed as fish. Otherwise it's displayed as slabs of meat. Internally both meat and fish are the same resource, the game just displays different graphics depending on whether the wharves are available or not.

It's addressed in the unstable: fish and meat are now separate resources so no more pig farms generating fish.

**Comment by MollyRenata** [comment]
Ah, thanks. I didn't stop to think of the possibility that wharves being allowed was the problem!

**Comment by Keriew** [comment]
All right, with your question answered and the underlying problem already fixed in the unstable, I consider this resolved.
