### ISSUE TITLE
Issue with unofficial Czech translation (broken code page/broken accented chars)

### ISSUE THREAD

**Issue by jose1711** [Keriew/augustus#995]
I downloaded an unofficial fan-made Czech translation for Caesar 3 from https://community.pcgamingwiki.com/files/file/2828-unofficial-czech-language-for-caesar-3/ and replaced `C3.eng` file.

Augustus seems to have load it but there is an issue with encoding - problematic parts highlighted below:

![obrázok](https://github.com/Keriew/augustus/assets/1406222/7907bbde-1812-481d-987c-e1ff67c48e91)

It looks like that a translation uses latin2 (iso8859-2) and Augustus expects latin1, but not quite:
```
>>> 'Zobrazit dosah při stavbě nádrží, fontán a studní'.encode('latin2').decode('latin1')
'Zobrazit dosah pøi stavbì nádr¾í, fontán a studní'
```
Please compare `¾` to `ñ`.

As I haven't found a way in Augustus to force certain encoding I would like to ask if there is any chance for a patch/workaround.

**Comment by crudelios** [comment]
Hi,

Are you using the stable v3.2.0?

Czech support has been added since the latest release and should be available on the unstable build.

**Comment by jose1711** [comment]
Hello @crudelios 

I am using `Augustus version 3.2.0.725-6b86cd6c, x64 build` (AppImage), this version offered by `Lutris` 0.5.14 during the installation of Caesar 3 from GOG. When I go to options I only see "default" language available, perhaps that's the issue?

Thanks, jose

**Comment by crudelios** [comment]
It may precisely be because you're loading the files to the original image and loading as (default).

Since Linux has case sensitive files, most likely your game is loading the english version of the images.

Get the translation files to a folder named "Czech" on your C3 installation and then on the options menu load the "Chech" language. Don't forget to delete the Czech files from the original C3 folder (watch out not to delete the english language files, you can do it by case comparing the CZ files and only remove the ones that exactly match.

Also, very important: please get the latest unsable version of augustus (added today) as it fixes a nasty crash related with loading the Czech image files (the files are improperly formatted which caused a crash on augustus).

Finally: [Check here for more Czech translations](https://github.com/bvschaik/julius/issues/679), including video files and the map editor.

**Comment by jose1711** [comment]
Thank you, that answers my question. As quite a few strings are missing though - is there a way to add them to the translation?

**Comment by crudelios** [comment]
Yeah, you can check on `augustus-log.txt` which translations are missing and add them by grabbing the `src/translation/english.c` as a template and adding the missing strings to `czech.c`.

There are a lot of strings though!

**Comment by crudelios** [comment]
Since the main issue is now fixed (and an annoying crash as well), I'll be closing this now.
